### ISSUE TITLE
OpenAiId is undefined when creating a new assistant

### ISSUE THREAD

**Issue by Jamesllllllllll** [mdwiltfong/doc-inspector#11]
I get an Assistant successfully created, but the DB shows `null` for `openAiId`. I tried it in Postman and got the same result.

The last time it was working was 24 hours ago. I just merged the PR, so it could be that? 

I don't see anything in the code that should affect the `openAiId`. I didn't try creating an assistant today before merging.

**Comment by mdwiltfong** [comment]
Resolved!
