### ISSUE TITLE
Changed one line in routes/threads/POST-message.js

### ISSUE THREAD

**Issue by Jamesllllllllll** [mdwiltfong/doc-inspector#6]
Not sure how it will work when you `ggt sync` - if it will pull my change that I made in the Gadget UI.

I changed [line 19 in routes/threads/POST-message.js](https://github.com/mdwiltfong/doc-inspector/blob/821ca238735f89a14c1d243c215a1d98e0e33973/routes/threads/POST-message.js#L19)

It was using `external_id` when adding the message to the thread in OpenAI, but it actually needed the `openAIId`.

Response:
```js
Object { message: "Message added" } // Woo!
```

**Comment by Jamesllllllllll** [comment]
So funny, I just re-read our convo from last night, and the error with the `external_id` was because it had the OpenAI assistant ID. I feel my the above change is just shifting the issue, because you _did_ have the `external_id` as the assistant ID.

ANYWAY, it works. 😄

**Comment by mdwiltfong** [comment]
Thanks!
